### ISSUE TITLE
Adicionar logo da pybr 2022 no pythonbrasil-2022/README.md

### ISSUE THREAD

**Issue by jtemporal** [pythonbrasil/talks#113]
A logo pode ser [encontrada aqui](https://raw.githubusercontent.com/akrs3/pythonbrasil-talks/de881504bdd3eff24337ce694466996b2f320a96/pythonbrasil-2022/logo-pybr22.svg)

**Comment by lahiss** [comment]
> A logo pode ser [encontrada aqui](https://raw.githubusercontent.com/akrs3/pythonbrasil-talks/de881504bdd3eff24337ce694466996b2f320a96/pythonbrasil-2022/logo-pybr22.svg)

Oiee, seria nesse [readme aqui](https://github.com/pythonbrasil/pybr2022-org#readme), certo?

**Comment by rougeth** [comment]
@lahiss esse aqui https://github.com/pythonbrasil/talks/blob/master/pythonbrasil-2022/README.md

Olha como foi feito no de 2019.
