### ISSUE TITLE
Linkar em cada palestra, o vídeo (se disponível)

### ISSUE THREAD

**Issue by gilsondev** [pythonbrasil/talks#15]

**Comment by rougeth** [comment]
@gilsondev se vc puder, dá pra começar a linkar as palestras de 2015 (:

**Comment by gilsondev** [comment]
Beleza man ;)

**Comment by gilsondev** [comment]
Fiz o link das apresentações que encontrei no Youtube, do Python Brasil [11]. Segue o PR #32.

**Comment by rougeth** [comment]
Valeu @gilsondev!
