### ISSUE TITLE
Add descrição da palestra das Pyladies

### ISSUE THREAD

**Issue by jtemporal** [pythonbrasil/talks#42]
Criar repo com a descrição e tal da palestra da Pyladies q tem o link add por #40

**Comment by jtemporal** [comment]
descricao pode ser encontrada [aqui](https://speakerfight.com/events/python-brasil-13-palestras/#pyladies-e-django-girls-promovendo-a-diversidade-na-tecnologia)

**Comment by deboraazevedo** [comment]
I'll take that :)
