### ISSUE TITLE
Podemos adicionar LTs e OpenSpaces?

### ISSUE THREAD

**Issue by rochacbruno** [pythonbrasil/talks#44]
O que acham de adicionar Lightining talks e Open Spaces?

**Comment by jtemporal** [comment]
Opa! devemos... se abrir o [README.md](/pythonbrasil/talks/blob/master/pythonbrasil-13/README.md) da pra ver que tem as sessão de palestra relâmpago comentada =) 

pra mim ta valendo colocar os dois ;)
