### ISSUE TITLE
Guia de contribuição

### ISSUE THREAD

**Issue by rsip22** [pythonbrasil/talks#81]
Não tem um guia para as pessoas enviarem seus Pull-requests.

Tem alguma padronização?

Forma de contribuir que não baixando os 100mb de arquivos desse repositório?

**Comment by rougeth** [comment]
Sim, há padronização, as pastas de cada ano da Python Brasil são no mesmo formato `pythonbrasil-yy`, e o `README.md` dentro de cada uma dessas pastas seguem o mesmo modelo, título com link para as palestras separadas por cada dia da conferência.

Mas de fato não há uma forma de contribuir sem baixar o repositório inteiro. Alguma sugestão nesse ponto? Talvez integrar com Google Forms (ou serviço semelhante) facilite.

**Comment by jtemporal** [comment]
Acho que da também pra criar um template de pull request pra lembrar as pessoas de por exemplo, alem de criar uma pastinha da palestra linkar a palestra no README.md de cada ano.

**Comment by jtemporal** [comment]
Vou fechar essa issue aqui ja que temos um CONTRIBUTING.md funcional
